### PR TITLE
Add toggleterm repl

### PR DESCRIPTION
**Pull request by cnrrobertson**
This PR establishes a format for adding more repl providers than just `iron.nvim` and adds `toggleterm.nvim` as an example. Addresses #2.

Mirrors the idea of the various commenters by searching for installed `iron` or `toggleterm` rather than adding a new configuration option. Seemed more convenient. However, it is possible that someone has both installed and wants to select the repl..

### CODE REVIEW

**Comment by GCBallesteros** [comment]
Thanks for the PR! I will do some testing and come back with a code review although from a first quick inspection things look really fine.

The one thing I would try to address is the configuration for the choice of REPL. What do you think of having a config parameter such as `repl_priority` which takes an array of REPL providers? The providers would then be checked and chosen in the order specified.

**Comment by cnrrobertson** [comment]
Yeah I'm open to either a `repl_priority` or even a `repl_provider` that explicitly gives the provider. 

However, I think if we grab a config value for the repls we will have a loop because `init.lua` imports `core.lua` which imports `repls.lua` which would import `init.lua` to get the config value. This is something I've run into before with lua plugins but have never found a good way around.

**Comment by GCBallesteros** [comment]
One way to avoid the circular import is to encapsulate the logic between lines 39 and 49 of `repls.lua` [*] into a `get_repl(repl_provider)` function which is returned from the module instead of the bare `repl`. Then in `core.lua` we would  use `get_repl` by replacing the call to 

```lua
repl(cell_object.from.line, cell_object.to.line, repl_args)
```
with

```lua
get_repl(repl_provider)(cell_object.from.line, cell_object.to.line, repl_args)
```

This also means changing the signature of `run_cell` and `run_and_move` so that then they can use `M.config.repl_provider` inside `init.lua`. This, by itself, is a breaking change, but can be sidestepped for now by having a default value for `repl_provider` of `auto`(see below).

I think this would be a clean way to go about the problem you are describing above and will probably implement it for the commenters too.

A question remaining would be what to use as config parameter. I like better your `repl_provider` than my `repl_priority`, the only tweak I would add is to have as options: __`auto`__, `toggleterm` and `iron`. `auto` would try to fetch one in the order they were added to the codebase like we are doing now.


[*] and between 25 and 36 of `commenters.lua`

**Comment by GCBallesteros** [comment]
Hi, I just tested the code and found a bug on `get_repl`. Now it fails when a `repl_provider` other than `auto` is passed. Here is the code:

```lua
local get_repl = function(repl_provider)
  local repl_providers = {"iron", "toggleterm"}
  if repl_provider == "auto" then
    for _,r in ipairs(repl_providers) do
      if pcall(require, r) then
        return repls[r]
      end
    end
  elseif repl_providers[repl_provider] then  -- <--- 🐛 BUG 🐛
      if pcall(require, repl_provider) then
        return repls[repl_provider]
      end
  else
    return repls["no_repl"]
  end
end
```
`repl_providers` is an array but here we are attempting to index it with a string which results in `nil` and therefore you always end up in the no repl case. I suggest:

```lua
local get_repl = function(repl_provider)
  local repl_providers = { "iron", "toggleterm" }
  if repl_provider == "auto" then
    for _, r in ipairs(repl_providers) do
      if pcall(require, r) then
        return repls[r]
      end
      vim.notify "[Notebook Navigator] None of the supported REPL providers is available. Please install iron or toggleterm"
    end
  else
    if pcall(require, repl_provider) then
      return repls[repl_provider]
    else
      vim.notify("[Notebook Navigator] The " .. repl_provider .. " REPL provider is not available.")
    end
  end
  return repls["no_repl"]
end
```

I removed the bad `if` and added some extra notifications explaining why things may not be working. I also modified `repl.no_repl` so that one doesn't get a double notification when no REPL was found to:

```lua
repls.no_repl = function(_) end
```

Another thing that could be improved is that, when using Toggleterm, the first time a cell gets execute the terminal pops up and text gets sent to it but since no REPL is running it ends up in a confused shell. I will still merge the PR if this doesn't get fixed, an issue can be opened and leave it as future work.

**Comment by cnrrobertson** [comment]
Ah good catch. I think the re-write looks excellent.

Keeping track of a repl in toggleterm is tricky given there isn't a good way to mark whether you have activated a REPL in the terminal or when that REPL is closed. The best I've been able to work out is to start the terminal with a REPL command (like `ipython`) so that it is guaranteed to be active but it is not easy to work that into the `exec` command for toggleterm that I use here. 

To be completely honest, I've been using toggleterm for about a year for repls in a few languages (python, julia, r, lua) but recently - in the last couple weeks - have switched to a plugin I wrote to replace toggleterm that would make it easier to keep track of repls and easier to send lines to. I was hoping this PR would pave the way for integration with that plugin and get toggleterm working for others who might be interested. But honestly, at this point, I'd be okay to not merge this and I could submit a new PR integrating with that with this exact same repl abstraction design. Or, if you're happy with how this looks after the changes, it can be merged and I can submit another PR later with the new plugin.

**Comment by GCBallesteros** [comment]
I think the PR is still valuable as it is and puts in place a nice and easy to use framework for future integrations. One last thing before merging. Would you mind doing the modifications described above and finish by squashing your commits into a single one of the form:
```
feat: Add toggleterm.vim support

More detailed description of things that have been done to get this working.
```

That way the git history stays nice and tidy.

I could do a squash and merge myself on the GH interface but I don't know if by doing that I would "destroy" your contribution which would be a pity.

Thanks for contributing!

**Comment by tmke8** [comment]
In order to use `toggleterm`, I had to set `shell = "ipython"` in the config of toggleterm. Is that how it is? Or should this work without additional configuration?

**Pull request merged**
