### PR TITLE
`%%` comments as default cell markers

### LINKED ISSUE #23: Suggestion: Use double-percent comments as default cell markers
Instead of defining cell markers manually for every language, one could use `:h commentstring` and fill in `%%` as a de facto standard (e.g. [outlined by jupytext](https://jupytext.readthedocs.io/en/latest/formats-scripts.html#the-percent-format)).

That simplify the plugin config, and also make cell markers available without the need for the user to set anything up. That way, the plugin could be used out of the box for most languages, e.g. when you want to work "notebook-style" with javascript

```lua
-- determine the cell marker for any language
cell_marker = vim.bo.commentstring:format("%%")
```

### PR DESCRIPTION
**Pull request by chrisgrieser**
closes #23

### CODE REVIEW

**Comment by GCBallesteros** [comment]
Thanks for the PR!

Haven't tested it yet but looks good. Will merge as soon as I do that final check.

**Comment by GCBallesteros** [comment]
After some testing and closer inspection I've found the following issues with the PR:
1.  Breaks the mini.hipatterns integration to highlight the cell marker lines, more specifically the problem is on this [line](https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/0a5f7d4329eec573a967a4c0c7b3d47050502dc2/lua/notebook-navigator/highlight.lua#L9C27-L9C47). That function should  use the `utils.get_cell_marker` function instead of relying directly on `config.cell_markers`. For reference that code within `highlight.lua` is called at the bottom of `init.lua` to generate the spec for hipatterns. This was okay before and hence why it passed unnoticed but this PR has triggered the latent bug sorry for that. Do you mind addressing this issue (even if it's only my fault)? Otherwise I will just build on top of your commits once I have some bandwidth.
2. `doc/NotebookNavigator.txt` hasn't been updated.

Thanks again!

**Comment by chrisgrieser** [comment]
1. No problem, fixed.
2. Thought the file was auto-generated. :P 
Anyway, also modified the respective section of the help docs.

**Comment by GCBallesteros** [comment]
Looks good and works!

With respect to the docs. I usually generate them with miniDoc but I run it manually because I haven't taken the time to figure out how to autmate it yet.

**Pull request merged**
