### PR TITLE
Additional cell operations

### PR DESCRIPTION
**Pull request by cnrrobertson**
Addresses new features discussed in #6

### CODE REVIEW

**Comment by GCBallesteros** [comment]
That's a lot of new functions! I will test them out as soon as I can. I'm thinking that it would be nice to be able to specify exactly which of all the available functions end up being mapped in the hydra mode. That way one can eliminate the functionality you may not be interested. Once I've tested the code I will merge it into a new branch and add start working on it.

**Comment by cnrrobertson** [comment]
Yeah no worries, no rush. None of them are too complicated. But adding all of them does really crowd the Hydra menu... I like the idea of selectively adding (or removing) ones you don't really care about.

**Comment by GCBallesteros** [comment]
While developing the feature to disable mappings I realized that doing it well requires one of the following:
1. Generating they hydra hint on the fly.
2. Asking the user to provide their own hint if they want to change ANY default.
3. Disable the hint.

I will start with option 2 above and then merge the changes proposed on this PR but with all the extra functions disabled. Then I will add instructions on what has to be done if one wants to activate them.

**Comment by cnrrobertson** [comment]
Sounds great. 

I wonder if there is a nice way to have a user pass in a table of desired options and then auto-generate the hint with good spacing. Maybe that's what you meant with 1.

**Comment by GCBallesteros** [comment]
Indeed, that's what I meant with option 1. It has more sharp edges than the Iron Throne and I'm dreading implementing it :) I have the eery feeling that the code to accomplish it will end up with more LOC than the actual plugin.

**Comment by GCBallesteros** [comment]
@cnrrobertson I'm integrating some of the functions you created in this PR into another branch. My plan is to add just one or two of them into hydra interface and default keybindings and make the rest accesible only as functions in the plugin. 

This branch has diverged far enough from main that it is easier for me to just copy-paste the functions than to go through merges. However, and unfortunately, that does mean that your contribution is not recorded on the repo's history. Is there some way that you can think of to correct this. Some options:

1. I make a PR to your fork and once merged and accepted and merged on your side you make a PR here.
2. I make a new branch (done but not pushed to github) here and then you do a PR into that branch with some dummy commits that once merge I  can squash and finally merge the branch into main.

**Comment by cnrrobertson** [comment]
Yeah no worries! I’m really just looking for the functionality. Not worried about the contribution credit. 

Excited to have these in though! I’ve been waiting to fully migrate from my own hacked together cell functionality. I think it’s time

**Pull request closed without merging**
